language: java

addons:
  sonarcloud:
    organization: "sajjaadalipour"

services:
  - redis

matrix:
  include:
    - jdk: openjdk8
      os: linux
      env: JAVA_VERSION=1.8
      script:
        - chmod +x mvnw
        - ./mvnw clean verify
    - jdk: openjdk9
      os: linux
      env: JAVA_VERSION=9
    - jdk: openjdk10
      os: linux
      env: JAVA_VERSION=10
      script:
        - chmod +x mvnw
        - ./mvnw clean verify
    - jdk: openjdk11
      os: linux
      env: JAVA_VERSION=11
      script:
        - chmod +x mvnw
        - ./mvnw clean verify sonar:sonar -Dsonar.projectKey=sajjaadalipour_ratelimit-spring-boot-starter
        - bash <(curl -s https://codecov.io/bash)

install: true

cache:
  directories:
    - $HOME/.m2/repository